{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} | json"
    }
   ]
  },
  {
   "title": "Active User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "Active Users" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "description": "This is the first one for the deliverable.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_get_total[1m])",
     "legendFormat": "Get"
    },
    {
     "expr": "rate(http_requests_post_total[1m])",
     "legendFormat": "Post"
    },
    {
     "expr": "rate(http_requests_put_total[1m])",
     "legendFormat": "Put"
    },
    {
     "expr": "rate(http_requests_delete_total[1m])",
     "legendFormat": "Delete"
    },
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "all" }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage_percent", "legendFormat": "CPU Usage" },
    { "expr": "memory_usage_percent", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(auth_successful_total[1m])",
     "legendFormat": "successful"
    },
    { "expr": "rate(auth_failed_total[1m])", "legendFormat": "failed" }
   ]
  },
  {
   "title": "Pizza Revenue Total / Mintue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "rate(pizza_revenue_total[1m])", "legendFormat": "Pizza Revenue" }
   ]
  },
  {
   "title": "Pizza Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(pizzas_sold_total[1m])", "legendFormat": "Pizza Purchases" },
    { "expr": "pizza_failures_total", "legendFormat": "Purchase Failures" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "Service endpoint\nPizza creation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "service_latency_milliseconds", "legendFormat": "Request Latency" }
   ]
  }
 ]
}